# Data Exploration & Preprocessing

### Observations

### Data Preprocessing Steps
- Combine the three datasets into a single `.csv` with the dataset folder in the file path
- create an output `.json` file with Common Name & Scientific Name using ebird code as the key
- Remove any unwanted labels, such as 'spybird' from the secondaries, or anything not in the primaries

In [788]:
from pathlib import Path
import pandas as pd
import plotly.express as px
import json
from tqdm.notebook import tqdm
from collections import Counter
from IPython.display import Audio
import ast

In [789]:
class FilePaths:
    PROJECT_FOLDER = Path('/media/olly/T7/Kaytoo')
    DATA_FOLDER = PROJECT_FOLDER / 'Data'
    DS_TONE = DATA_FOLDER / 'Train_Tier1'
    DS_GRAE = DATA_FOLDER / 'Train_Graeme_Elliot'
    DS_XENO = DATA_FOLDER / 'Train_Xeno_Canto'
    METADATA_TONE = DS_TONE / 'tier1_metadata.csv'
    METADATA_GRAE = DS_GRAE / 'graeme_elliot_metadata.csv'
    METADATA_XENO = DS_XENO / 'xc_metadata.csv'
    OUTPUT_CSV_PATH = DATA_FOLDER / 'Train_Metadata/train_metadata.csv'
    OUTPUT_NAMING_CSV_PATH = DATA_FOLDER / 'Train_Metadata/bird_naming.csv'
    OUTPUT_JSON_PATH = DATA_FOLDER / 'Train_Metadata/kaytoo_bird_names.json'
    BIRD_NAME_MAP = DATA_FOLDER / 'Bird_Names/bird_map_corrected.csv'

In [790]:
class DefaultConfiguration:
    REMOVE_BELOW_THRESHOLD = 5
    SR = 32000
    MERGERS = {'oyster1':['varoys1', 'soioys1', 'blkoys'],
                'parake':['yefpar3', 'refpar4', 'malpar2']}

Now I'm going to extract these configuration settings to variables for the rest of the script.  Doing it this way to make it consistancy with the rest of the project, and so that the analysis can be updated for any changes in dataset settings.

In [791]:
paths = FilePaths()
cfg = DefaultConfiguration()

In [792]:
use_cols = ['filename', 'primary_label', 'secondary_labels', 'start', 'end', 'source_fn']
df_1 = pd.read_csv(paths.METADATA_TONE, usecols=use_cols)
df_1['filename'] = 'Train_Tier1/train_audio/' + df_1['filename'] 
df_2 = pd.read_csv(paths.METADATA_GRAE, usecols=use_cols)
df_2['filename'] = 'Train_Graeme_Elliot/train_audio/' + df_2['filename'] 
df_3 = pd.read_csv(paths.METADATA_XENO, usecols=use_cols)
df_3['filename'] = 'Train_Graeme_Elliot/train_audio/' + df_3['filename'] 
print(f'There are {len(df_1)} rows from Tier 1 data')
df_1.head()

There are 144733 rows from Tier 1 data

,filename,primary_label,secondary_labels,start,end,source_fn
0,Train_Tier1/train_audio/yefpar3/AE142_BIRP_120...,yefpar3,['pipipi1'],659,664,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
1,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,[],666,671,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
2,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['nezbel1', 'nezfan1']",680,689,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
3,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['gryger1', 'nezbel1', 'tomtit1']",699,704,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
4,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['nezbel1', 'silver3', 'tomtit1']",709,718,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...

In [793]:
df_2.head()

,filename,primary_label,secondary_labels,start,end,source_fn
0,Train_Graeme_Elliot/train_audio/riflem1/00024E...,riflem1,[],3.0,7.0,Paringa 2010/all 30 min counts/{guid {00024E7C...
1,Train_Graeme_Elliot/train_audio/silver3/00024E...,silver3,[],27.0,32.0,Paringa 2010/all 30 min counts/{guid {00024E7C...
2,Train_Graeme_Elliot/train_audio/gryger1/00024E...,gryger1,[],49.0,53.0,Paringa 2010/all 30 min counts/{guid {00024E7C...
3,Train_Graeme_Elliot/train_audio/riflem1/00024E...,riflem1,['tomtit1'],116.0,120.0,Paringa 2010/all 30 min counts/{guid {00024E7C...
4,Train_Graeme_Elliot/train_audio/tomtit1/00024E...,tomtit1,[],147.0,152.0,Paringa 2010/all 30 min counts/{guid {00024E7C...

In [794]:
print(f'There are {len(df_2)} rows in the Graeme Elliot data')

There are 145441 rows in the Graeme Elliot data

In [795]:
df_3.head(3)

,filename,primary_label,secondary_labels,start,end,source_fn
0,Train_Graeme_Elliot/train_audio/silver3/silver...,silver3,['spybird'],0.0,12.0,XC895593_Zosterops_lateralis.mp3
1,Train_Graeme_Elliot/train_audio/silver3/silver...,silver3,['spybird'],0.0,12.0,XC841102_Zosterops_lateralis.mp3
2,Train_Graeme_Elliot/train_audio/silver3/silver...,silver3,[],0.0,12.0,XC836020_Zosterops_lateralis.mp3

In [796]:
print(f'There are {len(df_3)} rows in the Xeno Canto data')

There are 2838 rows in the Xeno Canto data

In [797]:
df=pd.concat([df_1, df_2])  #, df_3
df.head()

,filename,primary_label,secondary_labels,start,end,source_fn
0,Train_Tier1/train_audio/yefpar3/AE142_BIRP_120...,yefpar3,['pipipi1'],659.0,664.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
1,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,[],666.0,671.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
2,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['nezbel1', 'nezfan1']",680.0,689.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
3,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['gryger1', 'nezbel1', 'tomtit1']",699.0,704.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
4,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['nezbel1', 'silver3', 'tomtit1']",709.0,718.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...

In [798]:
len(df)

290174

## Merge Some Rare Classes

The filepaths will be left the same, we're just going to change the labels.

In [799]:
old_names = all_items = [item for sublist in cfg.MERGERS.values() for item in sublist]
inverted_names = {item: key for key, value_list in cfg.MERGERS.items() for item in value_list}
df['secondary_labels'] = df['secondary_labels'].apply(ast.literal_eval)

mask_1 = (df['primary_label'].isin(old_names))
mask_2 = df['secondary_labels'].apply(lambda x: any(item in old_names for item in x))
len(df[mask_1+ mask_2])

537

In [800]:
df.head(3)

,filename,primary_label,secondary_labels,start,end,source_fn
0,Train_Tier1/train_audio/yefpar3/AE142_BIRP_120...,yefpar3,[pipipi1],659.0,664.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
1,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,[],666.0,671.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
2,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"[nezbel1, nezfan1]",680.0,689.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...

In [801]:
df[df['secondary_labels'].isna()]

Empty DataFrame
Columns: [filename, primary_label, secondary_labels, start, end, source_fn]
Index: []

In [802]:
df[mask_2]

,filename,primary_label,secondary_labels,start,end,source_fn
244,Train_Tier1/train_audio/yellow3/AI137_BIRX_120...,yellow3,"[tomtit1, yefpar3]",619.0,624.0,Tier1_ARDs_2011-12/2011-12_5MBC/AI137_BIRX_120...
249,Train_Tier1/train_audio/yellow3/AI137_BIRX_120...,yellow3,"[nezfan1, pipipi1, silver3, yefpar3]",859.0,864.0,Tier1_ARDs_2011-12/2011-12_5MBC/AI137_BIRX_120...
7790,Train_Tier1/train_audio/yellow3/AI137_BIRM_120...,yellow3,"[nezbel1, tomtit1, yefpar3]",103.0,108.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/AI137_BIRM_...
7793,Train_Tier1/train_audio/yellow3/AI137_BIRM_120...,yellow3,"[riflem1, tomtit1, yefpar3]",275.0,280.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/AI137_BIRM_...
8013,Train_Tier1/train_audio/yellow3/AI137_BIRX_120...,yellow3,"[silver3, tomtit1, yefpar3]",105.0,110.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/AI137_BIRX_...
16891,Train_Tier1/train_audio/ausmag2/CS77_BIRD_1111...,ausmag2,"[comcha, eurbla, gryger1, riflem1, yefpar3]",317.0,326.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/CS77_BIRD_1...
16892,Train_Tier1/train_audio/ausmag2/CS77_BIRD_1111...,ausmag2,"[comcha, dunnoc1, eurbla, yefpar3]",336.0,341.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/CS77_BIRD_1...
16893,Train_Tier1/train_audio/ausmag2/CS77_BIRD_1111...,ausmag2,"[comcha, yefpar3]",343.0,348.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/CS77_BIRD_1...
17156,Train_Tier1/train_audio/ausmag2/CS77_BIRX_1111...,ausmag2,[yefpar3],262.0,268.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/CS77_BIRX_1...
17159,Train_Tier1/train_audio/ausmag2/CS77_BIRX_1111...,ausmag2,[yefpar3],312.0,317.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/CS77_BIRX_1...
17160,Train_Tier1/train_audio/ausmag2/CS77_BIRX_1111...,ausmag2,"[eurbla, gryger1, yefpar3]",332.0,338.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/CS77_BIRX_1...
21534,Train_Tier1/train_audio/yellow3/N165_BIRA_1112...,yellow3,"[tomtit1, yefpar3]",146.0,151.0,Tier1_ARDs_2011-12/2011-12_DIURNAL/N165_BIRA_1...
83876,Train_Tier1/train_audio/houspa/BI128_BIRD_1312...,houspa,"[eurbla, maslap1, skylar, soioys1, yellow2]",56.0,61.0,Tier1_ARDs_2013-14/2013-14_DIURNAL/BI128_BIRD_...
83877,Train_Tier1/train_audio/houspa/BI128_BIRD_1312...,houspa,"[eurbla, maslap1, skylar, soioys1]",91.0,96.0,Tier1_ARDs_2013-14/2013-14_DIURNAL/BI128_BIRD_...
83878,Train_Tier1/train_audio/houspa/BI128_BIRD_1312...,houspa,"[comcha, eurbla, maslap1, soioys1, yellow2]",101.0,108.0,Tier1_ARDs_2013-14/2013-14_DIURNAL/BI128_BIRD_...
83881,Train_Tier1/train_audio/houspa/BI128_BIRD_1312...,houspa,"[soioys1, yellow2]",205.0,210.0,Tier1_ARDs_2013-14/2013-14_DIURNAL/BI128_BIRD_...
83891,Train_Tier1/train_audio/houspa/BI128_BIRD_1312...,houspa,"[eurbla, eursta, soioys1]",306.0,313.0,Tier1_ARDs_2013-14/2013-14_DIURNAL/BI128_BIRD_...
83892,Train_Tier1/train_audio/houspa/BI128_BIRD_1312...,houspa,"[comcha, eurbla, soioys1, yellow2]",315.0,322.0,Tier1_ARDs_2013-14/2013-14_DIURNAL/BI128_BIRD_...

In [803]:
old_names

['varoys1', 'soioys1', 'blkoys', 'yefpar3', 'refpar4', 'malpar2']

In [804]:
inverted_names['yefpar3']

'parake'

In [805]:
def merge_secondaries(labels, reverse_map=inverted_names, merger_vals = old_names):
    print(labels)
    return [reverse_map[item] if item in merger_vals else item for item in labels]

df.loc[mask_1, 'primary_label'] = df.loc[mask_1, 'primary_label'].map(inverted_names)
df.loc[mask_2, 'secondary_labels'] = df.loc[mask_2, 'secondary_labels'].apply(merge_secondaries)

['tomtit1', 'yefpar3']
['nezfan1', 'pipipi1', 'silver3', 'yefpar3']
['nezbel1', 'tomtit1', 'yefpar3']
['riflem1', 'tomtit1', 'yefpar3']
['silver3', 'tomtit1', 'yefpar3']
['comcha', 'eurbla', 'gryger1', 'riflem1', 'yefpar3']
['comcha', 'dunnoc1', 'eurbla', 'yefpar3']
['comcha', 'yefpar3']
['yefpar3']
['yefpar3']
['eurbla', 'gryger1', 'yefpar3']
['tomtit1', 'yefpar3']
['eurbla', 'maslap1', 'skylar', 'soioys1', 'yellow2']
['eurbla', 'maslap1', 'skylar', 'soioys1']
['comcha', 'eurbla', 'maslap1', 'soioys1', 'yellow2']
['soioys1', 'yellow2']
['eurbla', 'eursta', 'soioys1']
['comcha', 'eurbla', 'soioys1', 'yellow2']

In [806]:
primary_list = sorted(list(df.primary_label.unique()))
primary_list = list(map(str, primary_list) )
primary_list.sort()
print(f'First 5 items of the species list: {primary_list[:5]}')
print(f'Total classes, extracted from the filepaths: {len(primary_list)}')

First 5 items of the species list: ['antpar1', 'ausbit1', 'ausmag2', 'auspip3', 'aussho1']
Total classes, extracted from the filepaths: 106

In [807]:
df.head(3)

,filename,primary_label,secondary_labels,start,end,source_fn
0,Train_Tier1/train_audio/yefpar3/AE142_BIRP_120...,parake,[pipipi1],659.0,664.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
1,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,[],666.0,671.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
2,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"[nezbel1, nezfan1]",680.0,689.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...

## Remove Unwanted Classes

In [808]:
def plot_class_distribution(df, plot_col='primary_label', title='primary_label frequency', height=400):
    total_counts = df[plot_col].value_counts().reset_index()
    total_counts.columns = [plot_col, 'total_count']
    fig = px.bar(total_counts, x=total_counts[plot_col], log_y=True, y=total_counts.total_count, template='seaborn',
    hover_data=[plot_col, 'total_count'], color=plot_col, height=height)
    fig.update_layout(title=title)
    fig.update_layout(showlegend=False)
    fig.update_xaxes(categoryorder='total descending')
    fig.show()

plot_class_distribution(df, plot_col='primary_label', title='Frequency by primary_label')

Let's generate a mapping file for the e-bird to get the scientific and common name in a consistent way

- load up the mapping files from Tier_1
- get a unique row for each ebird code, using the code from the primary_label list
- save the output to csv
- manually check the common names (since there isn't a 1-1 relationship)
- on re-loading, check that all the common names make sense

In [809]:
df_names = pd.read_csv(paths.BIRD_NAME_MAP)
df_names = df_names.drop_duplicates(keep='first', subset='eBird')
df_names = df_names.sort_values(by='eBird').reset_index(drop=True)[['eBird', 'CommonName','ScientificName']]
df_names.head(10)

     eBird              CommonName             ScientificName
0  ausbit1   Australasian Bittern      Botaurus poiciloptilus
1  ausgan1     Australasian Gannet             Morus serrator
2  ausmag2       Australian Magpie         Gymnorhina tibicen
3  auspip3       New Zealand Pipit     Anthus novaeseelandiae
4  aussho1   Australasian Shoveler         Spatula rhynchotis
5  baicra4             Marsh Crake           Zapornia pusilla
6  blafan1    South Island Fantail      Rhipidura fuliginosa
7  blasti1             Black Stilt  Himantopus novaezelandiae
8  blbgul1       Black-billed Gull    Chroicocephalus bulleri
9  blfdot1  Black-fronted Dotterel        Charadrius melanops

In [810]:
len(df_names)

138

In [811]:
df_names.to_csv(paths.OUTPUT_NAMING_CSV_PATH, index=False)
result_list = df_names.to_dict(orient='records')

with paths.OUTPUT_JSON_PATH.open('w') as file:
    json.dump(result_list, file, indent=4)

In [812]:
def map_names(row, mapping):
    common_name = mapping[row['primary_label']][0]
    scientific_name = mapping[row['primary_label']][1]
    return pd.Series([common_name, scientific_name], index=['common_name', 'scientific_name'])

df = df.merge(df_names, left_on='primary_label', right_on='eBird', how='left')
df.drop(columns=['eBird'], inplace=True)
df=df[['filename', 'primary_label', 'CommonName', 'secondary_labels', 'start', 'end', 'source_fn']]
df.head()

,filename,primary_label,CommonName,secondary_labels,start,end,source_fn
0,Train_Tier1/train_audio/yefpar3/AE142_BIRP_120...,parake,Parakeet,[pipipi1],659.0,664.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
1,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,Brown Creeper,[],666.0,671.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
2,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,Brown Creeper,"[nezbel1, nezfan1]",680.0,689.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
3,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,Brown Creeper,"[gryger1, nezbel1, tomtit1]",699.0,704.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...
4,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,Brown Creeper,"[nezbel1, silver3, tomtit1]",709.0,718.0,Tier1_ARDs_2011-12/2011-12_5MBC/AE142_BIRP_120...

In [813]:
df[df['secondary_labels'].isna()].shape

(0, 7)

In [814]:
plot_class_distribution(df, 
                        plot_col='CommonName', 
                        title='Frequency by common_name', 
                        height=800)

In [815]:
total_counts_primary = df['primary_label'].value_counts().reset_index()
total_counts_primary.tail(10)

    primary_label  count
96        yeepen1      1
97        grwpet2      1
98        barpar2      1
99        nezsca1      1
100       nezpig3      1
101       royalb2      1
102       whcalb1      1
103       sopsku1      1
104       stitch1      1
105       categr1      1

Just Checking if we drop the rarest parakeets it won't have a huge impact on the parakeet classes

In [816]:
total_counts_primary[total_counts_primary['primary_label'].isin(['antpar1', 'chipar1', 'malpar2', 'parake', 'refpar4', 'reipar1', 'yefpar3'])]

   primary_label  count
15        parake   2865
94       antpar1      2

So dropping malpar2 and antpar1 will have a negligable difference to the total number of parakeet class.  For now I'm going to just drop anything with less than 5 samples

In [817]:
len(df)

290174

In [818]:
mask = df['primary_label'].map(df['primary_label'].value_counts()) >= cfg.REMOVE_BELOW_THRESHOLD
df = df[mask]
total_counts_common_name = df['CommonName'].value_counts().reset_index()
total_counts_common_name.tail(10)

              CommonName  count
77       Eastern Rosella     11
78  Common Diving-Petrel      9
79      Domestic Chicken      7
80        Spotless Crake      6
81         Chatham Robin      6
82        Spotted Crake       5
83                Chukor      5
84          Black Petrel      5
85               Takahe       5
86          Caspian Tern      5

In [819]:
len(df)

290139

Also drop any with *badbird* or *spybird*

In [820]:
mask = df['primary_label'].isin(['badbird', 'spybird'])
print(len(df[mask]))

8

In [821]:
df=df[~mask]
len(df)

290131

In [822]:
plot_class_distribution(df, 
                        plot_col='CommonName', 
                        title='Frequency by common_name', 
                        height=600)

In [823]:
import ast
primary_list = df['primary_label'].unique()
def filter_list(secondaries, allowed):
    # Convert string representation of list to an actual list
    #actual_list = ast.literal_eval(list_str)
    # Filter the list
    filtered_list = [item for item in secondaries if item in allowed]
    return str(filtered_list)  # Convert back to string if needed

def filter_list(secondaries, allowed):
    if not isinstance(secondaries, (list, str)):
        return secondaries  # Return as is if it's not a list or string
    # Ensure secondaries is a list if it's a string
    if isinstance(secondaries, str):
        secondaries = eval(secondaries)  # Convert string representation of list to actual list
    # Filter the list
    filtered_list = [item for item in secondaries if item in allowed]
    return str(filtered_list)  # Convert back to string if needed




df['secondary_labels'] = df['secondary_labels'].apply(lambda x: filter_list(x, primary_list))

In [824]:
secondary_labels = df['secondary_labels'].to_list()
seconds_list = [eval(string) for string in secondary_labels]
flattened_seconds = [item for sublist in seconds_list for item in sublist]
item_counts = dict(Counter(flattened_seconds))
total_secondaries = len(flattened_seconds)
total_secondaries

110424

It would be good to plot this.

In [825]:
primary_list

array(['parake', 'pipipi1', 'nezfan1', 'gryger1', 'comcha', 'silver3',
       'nezbel1', 'tomtit1', 'eurgre1', 'riflem1', 'yellow3', 'eurbla',
       'nezrob3', 'kea1', 'tui1', 'nezpig2', 'nezrob2', 'shbcuc1',
       'nezkak1', 'eursta', 'sackin1', 'dunnoc1', 'lotkoe1', 'ausmag2',
       'blbgul1', 'kelgul', 'morepo2', 'oyster1', 'sobkiw2', 'mallar3',
       'rebgul1', 'grskiw1', 'nibkiw1', 'bluduc1', 'comred', 'eurgol',
       'chukar', 'nezfal1', 'sonthr1', 'yellow2', 'skylar', 'auspip3',
       'blfter1', 'cangoo', 'calqua', 'baicra4', 'weka1', 'fernbi1',
       'soiwre1', 'parshe1', 'maslap1', 'whfter1', 'whiteh1', 'saddle2',
       'takahe3', 'welswa1', 'chiger2', 'kokako3', 'swahar1', 'litowl1',
       'purswa6', 'commyn', 'houspa', 'charob1', 'x00458', 'piesti1',
       'ausbit1', 'redjun1', 'caster1', 'litpen1', 'liskiw1', 'motpet',
       'blkswa', 'gretea1', 'larus', 'easros1', 'rinphe1', 'compea',
       'dobplo1', 'aussho1', 'spocra2', 'okbkiw1', 'codpet1', 'coopet',
       'spocra1', 'parpet1', 'weta'], dtype=object)

In [826]:
len(primary_list)

87

In [827]:
unique_seconds = set(flattened_seconds)
len(unique_seconds)

51

In [828]:
df=df[['filename', 'primary_label', 'secondary_labels']]
df.head()

,filename,primary_label,secondary_labels
0,Train_Tier1/train_audio/yefpar3/AE142_BIRP_120...,parake,['pipipi1']
1,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,[]
2,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['nezbel1', 'nezfan1']"
3,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['gryger1', 'nezbel1', 'tomtit1']"
4,Train_Tier1/train_audio/pipipi1/AE142_BIRP_120...,pipipi1,"['nezbel1', 'silver3', 'tomtit1']"

In [836]:
list(df['secondary_labels'].unique())

["['pipipi1']",
 '[]',
 "['nezbel1', 'nezfan1']",
 "['gryger1', 'nezbel1', 'tomtit1']",
 "['nezbel1', 'silver3', 'tomtit1']",
 "['gryger1', 'nezbel1']",
 "['silver3']",
 "['gryger1', 'nezfan1', 'silver3']",
 "['gryger1']",
 "['nezbel1', 'tomtit1']",
 "['nezbel1']",
 "['comcha', 'nezbel1']",
 "['nezbel1', 'silver3']",
 "['tomtit1']",
 "['nezbel1', 'nezfan1', 'tomtit1']",
 "['gryger1', 'nezbel1', 'nezfan1']",
 "['nezbel1', 'riflem1']",
 "['riflem1', 'tomtit1']",
 "['gryger1', 'tomtit1']",
 "['comcha', 'gryger1', 'riflem1']",
 "['comcha']",
 "['comcha', 'tomtit1']",
 "['silver3', 'tomtit1']",
 "['tomtit1', 'parake']",
 "['pipipi1', 'riflem1']",
 "['pipipi1', 'riflem1', 'silver3']",
 "['nezfan1', 'pipipi1', 'silver3', 'parake']",
 "['nezfan1', 'pipipi1', 'riflem1', 'tomtit1']",
 "['comcha', 'pipipi1', 'riflem1']",
 "['pipipi1', 'riflem1', 'silver3', 'tomtit1']",
 "['riflem1']",
 "['comcha', 'riflem1']",
 "['riflem1', 'silver3', 'tomtit1']",
 "['nezfan1']",
 "['nezfan1', 'riflem1']",
 "['comcha', 'gryger1']",
 "['gryger1', 'silver3']",
 "['eurbla', 'gryger1']",
 "['eurbla']",
 "['comcha', 'gryger1', 'tomtit1']",
 "['comcha', 'gryger1', 'nezbel1']",
 "['eurbla', 'silver3']",
 "['eurbla', 'silver3', 'tomtit1']",
 "['gryger1', 'silver3', 'tomtit1']",
 "['tui1']",
 "['comcha', 'nezbel1', 'tomtit1']",
 "['nezrob3']",
 "['comcha', 'silver3']",
 "['comcha', 'eurbla']",
 "['gryger1', 'riflem1']",
 "['comcha', 'nezbel1', 'riflem1', 'tomtit1']",
 "['comcha', 'nezbel1', 'riflem1', 'silver3']",
 "['comcha', 'gryger1', 'nezbel1', 'tomtit1']",
 "['comcha', 'silver3', 'tomtit1']",
 "['gryger1', 'nezbel1', 'silver3', 'tomtit1']",
 "['gryger1', 'nezfan1']",
 "['nezfan1', 'silver3']",
 "['comcha', 'eurbla', 'gryger1', 'silver3', 'tomtit1']",
 "['eurbla', 'nezbel1', 'silver3']",
 "['riflem1', 'silver3']",
 "['gryger1', 'tui1']",
 "['comcha', 'gryger1', 'silver3']",
 "['eurbla', 'nezbel1']",
 "['comcha', 'eurbla', 'silver3']",
 "['gryger1', 'nezbel1', 'silver3']",
 "['comcha', 'nezbel1', 'silver3']",
 "['lotkoe1', 'silver3']",
 "['gryger1', 'nezbel1', 'nezrob2', 'tomtit1']",
 "['lotkoe1', 'silver3', 'tomtit1']",
 "['lotkoe1']",
 "['comcha', 'dunnoc1', 'gryger1', 'tomtit1']",
 "['comcha', 'nezrob2']",
 "['nezrob2']",
 "['dunnoc1', 'nezbel1', 'silver3']",
 "['dunnoc1', 'nezbel1']",
 "['comcha', 'dunnoc1']",
 "['gryger1', 'nezbel1', 'riflem1']",
 "['comcha', 'gryger1', 'nezbel1', 'riflem1']",
 "['comcha', 'eurbla', 'nezbel1']",
 "['comcha', 'eurbla', 'tomtit1']",
 "['eurbla', 'tomtit1']",
 "['comcha', 'gryger1', 'nezbel1', 'nezrob2']",
 "['comcha', 'tui1']",
 "['comcha', 'nezrob2', 'tomtit1', 'tui1']",
 "['nezrob2', 'tomtit1', 'tui1']",
 "['nezrob2', 'tui1']",
 "['comcha', 'nezbel1', 'tui1']",
 "['tomtit1', 'tui1']",
 "['gryger1', 'nezrob2']",
 "['eurbla', 'gryger1', 'nezbel1', 'nezkak1']",
 "['eurbla', 'nezbel1', 'nezkak1']",
 "['eurbla', 'nezbel1', 'tomtit1']",
 "['eurbla', 'gryger1', 'nezbel1', 'tomtit1']",
 "['eurbla', 'gryger1', 'tomtit1']",
 "['nezkak1']",
 "['nezkak1', 'tomtit1']",
 "['nezbel1', 'tui1']",
 "['lotkoe1', 'nezbel1']",
 "['eurbla', 'gryger1', 'nezbel1']",
 "['lotkoe1', 'tomtit1']",
 "['comcha', 'lotkoe1']",
 "['nezbel1', 'riflem1', 'tomtit1']",
 "['riflem1', 'tomtit1', 'tui1']",
 "['nezbel1', 'nezkak1']",
 "['kea1', 'riflem1', 'tomtit1']",
 "['gryger1', 'nezbel1', 'riflem1', 'tui1']",
 "['gryger1', 'nezbel1', 'nezkak1', 'tomtit1']",
 "['gryger1', 'nezbel1', 'riflem1', 'tomtit1']",
 "['nezbel1', 'tomtit1', 'tui1']",
 "['nezkak1', 'silver3', 'tomtit1']",
 "['kea1', 'nezbel1', 'riflem1']",
 "['nezbel1', 'nezfan1', 'silver3']",
 "['nezfan1', 'tomtit1']",
 "['gryger1', 'riflem1', 'tomtit1']",
 "['gryger1', 'kea1', 'nezbel1']",
 "['comcha', 'gryger1', 'pipipi1']",
 "['eurbla', 'nezbel1', 'pipipi1', 'tomtit1']",
 "['gryger1', 'nezfan1', 'riflem1']",
 "['kea1', 'nezfan1', 'riflem1']",
 "['kea1', 'tomtit1']",
 "['kea1', 'riflem1']",
 "['nezbel1', 'tomtit1', 'parake']",
 "['riflem1', 'tomtit1', 'parake']",
 "['gryger1', 'pipipi1', 'riflem1']",
 "['gryger1', 'pipipi1']",
 "['gryger1', 'pipipi1', 'riflem1', 'tomtit1']",
 "['comcha', 'riflem1', 'silver3']",
 "['comcha', 'riflem1', 'tomtit1']",
 "['silver3', 'tomtit1', 'parake']",
 "['comcha', 'riflem1', 'silver3', 'tomtit1']",
 "['comcha', 'eurbla', 'gryger1']",
 "['comcha', 'gryger1', 'nezbel1', 'silver3']",
 "['eurbla', 'gryger1', 'silver3']",
 "['comcha', 'eurbla', 'gryger1', 'tomtit1']",
 "['eurbla', 'gryger1', 'tui1']",
 "['comcha', 'eurbla', 'gryger1', 'nezrob3', 'silver3']",
 "['nezbel1', 'nezrob3']",
 "['eurbla', 'gryger1', 'nezrob3']",
 "['eurbla', 'gryger1', 'nezbel1', 'nezrob3']",
 "['eurbla', 'nezrob3', 'tomtit1']",
 "['eurbla', 'riflem1']",
 "['eurbla', 'nezbel1', 'nezrob3', 'silver3', 'tomtit1']",
 "['gryger1', 'tomtit1', 'tui1']",
 "['gryger1', 'nezfan1', 'tomtit1']",
 "['eurbla', 'gryger1', 'silver3', 'tomtit1', 'tui1']",
 "['eurbla', 'nezbel1', 'nezrob3', 'silver3', 'tui1']",
 "['eurbla', 'gryger1', 'nezbel1', 'silver3']",
 "['eurbla', 'riflem1', 'silver3']",
 "['eurbla', 'nezrob3', 'riflem1', 'silver3', 'tomtit1']",
 "['eurbla', 'gryger1', 'nezbel1', 'riflem1']",
 "['eurbla', 'riflem1', 'silver3', 'tomtit1']",
 "['nezrob3', 'tomtit1']",
 "['comcha', 'nezrob3']",
 "['gryger1', 'nezrob3']",
 "['nezrob3', 'riflem1']",
 "['comcha', 'nezbel1', 'nezrob3', 'tomtit1']",
 "['comcha', 'nezbel1', 'silver3', 'tomtit1']",
 "['comcha', 'nezbel1', 'nezrob3']",
 "['comcha', 'eurbla', 'gryger1', 'nezbel1']",
 "['nezbel1', 'silver3', 'tui1']",
 "['comcha', 'eurbla', 'riflem1', 'silver3']",
 "['eurbla', 'tui1']",
 "['eurbla', 'nezbel1', 'silver3', 'tui1']",
 "['comcha', 'eurbla', 'nezbel1', 'silver3']",
 "['silver3', 'tui1']",
 "['nezrob3', 'riflem1', 'silver3']",
 "['riflem1', 'silver3', 'tui1']",
 "['nezbel1', 'riflem1', 'silver3']",
 "['gryger1', 'silver3', 'tomtit1', 'tui1']",
 "['silver3', 'tomtit1', 'tui1']",
 "['eurbla', 'silver3', 'tomtit1', 'tui1']",
 "['nezkak1', 'silver3', 'tomtit1', 'tui1']",
 "['eurbla', 'nezbel1', 'silver3', 'tomtit1']",
 "['eurbla', 'nezbel1', 'tomtit1', 'tui1']",
 "['eurbla', 'nezkak1', 'silver3', 'tomtit1']",
 "['gryger1', 'nezkak1', 'silver3', 'tomtit1', 'tui1']",
 "['eurbla', 'nezkak1', 'riflem1', 'silver3', 'tui1']",
 "['nezkak1', 'riflem1', 'silver3', 'tui1']",
 "['eurbla', 'nezkak1', 'tomtit1', 'tui1']",
 "['eurbla', 'riflem1', 'tomtit1', 'tui1']",
 "['eurbla', 'gryger1', 'riflem1', 'tomtit1', 'tui1']",
 "['eurbla', 'nezkak1', 'silver3']",
 "['nezkak1', 'riflem1', 'silver3']",
 "['nezkak1', 'riflem1', 'silver3', 'tomtit1']",
 "['eurbla', 'riflem1', 'tomtit1']",
 "['eurbla', 'silver3', 'tui1']",
 "['nezbel1', 'nezkak1', 'silver3']",
 "['nezkak1', 'silver3']",
 "['gryger1', 'nezbel1', 'nezkak1', 'silver3', 'tomtit1']",
 "['eurbla', 'nezkak1']",
 "['nezrob3', 'silver3']",
 "['gryger1', 'nezkak1', 'silver3']",
 "['gryger1', 'nezkak1']",
 "['nezbel1', 'nezrob3', 'tui1']",
 "['gryger1', 'nezbel1', 'tui1']",
 "['comcha', 'gryger1', 'silver3', 'tomtit1']",
 "['eurbla', 'tomtit1', 'tui1']",
 "['nezrob3', 'tui1']",
 "['nezrob3', 'tomtit1', 'tui1']",
 "['nezbel1', 'nezrob3', 'tomtit1']",
 "['eurbla', 'nezbel1', 'nezrob3', 'tomtit1']",
 "['eurbla', 'nezbel1', 'nezrob3', 'tomtit1', 'tui1']",
 "['eurbla', 'nezbel1', 'nezrob3']",
 "['eurbla', 'nezbel1', 'tui1']",
 "['comcha', 'eurbla', 'gryger1', 'silver3', 'tui1']",
 "['lotkoe1', 'riflem1']",
 "['lotkoe1', 'nezbel1', 'silver3']",
 "['gryger1', 'lotkoe1', 'nezbel1']",
 "['gryger1', 'lotkoe1']",
 "['comcha', 'lotkoe1', 'tomtit1']",
 "['comcha', 'lotkoe1', 'nezbel1', 'tomtit1']",
 "['lotkoe1', 'nezbel1', 'tomtit1']",
 "['eurbla', 'lotkoe1']",
 "['comcha', 'dunnoc1', 'eurbla', 'gryger1']",
 "['comcha', 'eurbla', 'gryger1', 'riflem1', 'parake']",
 "['comcha', 'dunnoc1', 'eurbla', 'parake']",
 "['comcha', 'parake']",
 "['comcha', 'dunnoc1', 'eurbla', 'gryger1', 'riflem1']",
 "['comcha', 'eurbla', 'gryger1', 'silver3']",
 "['nezrob2', 'silver3']",
 "['comcha', 'nezrob2', 'silver3']",
 "['parake']",
 "['eurbla', 'gryger1', 'parake']",
 "['comcha', 'eurbla', 'nezbel1', 'tomtit1']",
 "['dunnoc1', 'eurbla', 'nezbel1']",
 "['gryger1', 'nezbel1', 'tomtit1', 'tui1']",
 "['nezbel1', 'nezrob2']",
 "['gryger1', 'nezbel1', 'nezrob2', 'tui1']",
 "['nezbel1', 'nezrob2', 'tui1']",
 "['nezbel1', 'nezrob2', 'tomtit1']",
 "['gryger1', 'nezbel1', 'nezrob2']",
 "['eurbla', 'gryger1', 'riflem1', 'tomtit1']",
 "['comcha', 'gryger1', 'riflem1', 'tomtit1']",
 "['comcha', 'eurbla', 'gryger1', 'nezbel1', 'tomtit1']",
 "['nezfan1', 'tomtit1', 'tui1']",
 "['gryger1', 'lotkoe1', 'tomtit1']",
 "['gryger1', 'lotkoe1', 'tomtit1', 'tui1']",
 "['gryger1', 'lotkoe1', 'silver3']",
 "['morepo2', 'nezbel1']",
 "['morepo2', 'nezbel1', 'silver3']",
 "['lotkoe1', 'nezrob2', 'silver3', 'tomtit1']",
 "['lotkoe1', 'nezrob2', 'silver3']",
 "['lotkoe1', 'riflem1', 'tomtit1']",
 "['eurbla', 'nezkak1', 'tomtit1']",
 "['gryger1', 'nezkak1', 'tomtit1']",
 "['nezbel1', 'nezkak1', 'tomtit1']",
 "['eurbla', 'nezbel1', 'nezfan1']",
 "['comcha', 'eurbla', 'gryger1', 'lotkoe1']",
 "['comcha', 'lotkoe1', 'nezbel1']",
 "['riflem1', 'tui1']",
 "['gryger1', 'nezbel1', 'riflem1', 'silver3']",
 "['nezbel1', 'nezfan1', 'riflem1']",
 "['lotkoe1', 'riflem1', 'silver3', 'tomtit1']",
 "['kea1', 'silver3', 'tomtit1']",
 "['dunnoc1', 'tomtit1']",
 "['morepo2']",
 "['morepo2', 'nezkak1']",
 "['morepo2', 'tomtit1']",
 "['gryger1', 'morepo2', 'silver3']",
 "['lotkoe1', 'morepo2']",
 "['lotkoe1', 'morepo2', 'nezbel1']",
 "['eurbla', 'nezfan1']",
 "['eurbla', 'morepo2']",
 "['comred']",
 "['comred', 'silver3']",
 "['comcha', 'eurgre1']",
 "['comcha', 'pipipi1']",
 "['comred', 'skylar']",
 "['skylar']",
 "['sonthr1']",
 "['comcha', 'sonthr1']",
 "['eurbla', 'skylar']",
 "['eurgre1', 'skylar']",
 "['comred', 'eurbla']",
 "['comred', 'nezbel1', 'silver3']",
 "['comred', 'nezbel1', 'pipipi1', 'silver3']",
 "['comred', 'pipipi1']",
 "['comred', 'nezbel1']",
 "['comred', 'riflem1']",
 "['comred', 'gryger1', 'riflem1', 'silver3']",
 "['yellow2']",
 "['nezkak1', 'tui1']",
 "['eurgol']",
 "['comred', 'sackin1']",
 "['sackin1']",
 "['comred', 'gryger1', 'sackin1']",
 "['comcha', 'skylar']",
 "['silver3', 'sonthr1']",
 "['gryger1', 'sackin1']",
 "['comcha', 'nezfan1']",
 "['eurgre1']",
 "['eurgre1', 'gryger1']",
 "['skylar', 'yellow2']",
 "['eurbla', 'sackin1']",
 "['tomtit1', 'whiteh1']",
 "['sackin1', 'whiteh1']",
 "['nezbel1', 'sackin1', 'whiteh1']",
 "['sackin1', 'tui1']",
 "['eurbla', 'whiteh1']",
 "['whiteh1']",
 "['tui1', 'whiteh1']",
 "['nezbel1', 'whiteh1']",
 "['eurbla', 'tui1', 'whiteh1']",
 "['nezbel1', 'rebgul1', 'whiteh1']",
 "['saddle2', 'whiteh1']",
 "['nezfan1', 'whiteh1']",
 "['rebgul1', 'whiteh1']",
 "['sackin1', 'yellow2']",
 "['sackin1', 'sonthr1']",
 "['nezbel1', 'sackin1']",
 "['nezbel1', 'yellow2']",
 "['gryger1', 'nezbel1', 'yellow2']",
 "['gryger1', 'yellow2']",
 "['sonthr1', 'yellow2']",
 "['ausmag2', 'nezbel1', 'nezrob2', 'tui1']",
 "['ausmag2', 'whiteh1']",
 "['nezrob2', 'sackin1']",
 "['nezrob2', 'whiteh1']",
 "['nezrob2', 'sonthr1', 'tui1', 'whiteh1']",
 "['gryger1', 'whiteh1']",
 "['gryger1', 'nezbel1', 'sonthr1', 'yellow2']",
 "['comred', 'sonthr1']",
 "['dunnoc1', 'sonthr1']",
 "['gryger1', 'sonthr1']",
 "['comcha', 'eurbla', 'sonthr1']",
 "['comred', 'gryger1', 'sonthr1']",
 "['comred', 'gryger1']",
 "['comred', 'eurbla', 'gryger1']",
 "['comred', 'eurbla', 'silver3']",
 "['comcha', 'comred', 'eurbla']",
 "['silver3', 'yellow2']",
 "['gryger1', 'pipipi1', 'tomtit1']",
 "['comcha', 'pipipi1', 'tomtit1']",
 "['comcha', 'shbcuc1']",
 "['comcha', 'pipipi1', 'riflem1', 'tomtit1']",
 "['pipipi1', 'riflem1', 'tomtit1']",
 "['comcha', 'nezfan1', 'pipipi1']",
 "['kea1', 'sonthr1']",
 "['eurbla', 'kea1', 'sonthr1']",
 "['comcha', 'kea1']",
 "['kea1']",
 "['eurbla', 'kea1']",
 "['comcha', 'comred']",
 "['comcha', 'comred', 'nezbel1']",
 "['nezbel1', 'sonthr1']",
 "['comcha', 'lotkoe1', 'silver3']",
 "['silver3', 'skylar']",
 "['comcha', 'skylar', 'tui1']",
 "['eurbla', 'skylar', 'tui1']",
 "['nezfan1', 'skylar', 'tui1']",
 "['comcha', 'silver3', 'skylar']",
 "['skylar', 'sonthr1']",
 "['skylar', 'sonthr1', 'yellow2']",
 "['comcha', 'silver3', 'sonthr1']",
 "['nezbel1', 'skylar']",
 "['nezbel1', 'silver3', 'sonthr1']",
 "['gryger1', 'nezbel1', 'skylar']",
 "['nezbel1', 'skylar', 'sonthr1']",
 "['comcha', 'yellow2']",
 "['comred', 'dunnoc1', 'silver3']",
 "['comred', 'dunnoc1']",
 "['comred', 'pipipi1', 'yellow2']",
 "['comred', 'yellow2']",
 "['comred', 'tomtit1']",
 "['comred', 'eurgol']",
 "['comred', 'eurgre1']",
 "['comcha', 'eurgre1', 'silver3', 'sonthr1']",
 "['ausmag2']",
 "['dunnoc1']",
 "['eurbla', 'yellow2']",
 "['eurbla', 'skylar', 'sonthr1']",
 "['comcha', 'nezkak1', 'tomtit1']",
 "['comcha', 'nezkak1', 'silver3']",
 "['comcha', 'nezkak1']",
 "['comcha', 'nezkak1', 'silver3', 'tomtit1']",
 "['comcha', 'tomtit1', 'tui1']",
 "['comcha', 'nezbel1', 'tomtit1', 'tui1']",
 "['comcha', 'nezbel1', 'nezkak1']",
 "['comcha', 'nezbel1', 'nezkak1', 'silver3', 'tomtit1']",
 "['gryger1', 'lotkoe1', 'silver3', 'tomtit1']",
 "['eurgre1', 'silver3']",
 "['cangoo']",
 "['comred', 'tui1']",
 "['comcha', 'sackin1']",
 "['comcha', 'dunnoc1', 'skylar', 'sonthr1']",
 "['dunnoc1', 'skylar']",
 "['comcha', 'skylar', 'sonthr1']",
 "['dunnoc1', 'eurbla', 'skylar', 'sonthr1']",
 "['dunnoc1', 'eurbla', 'skylar']",
 "['comred', 'eurbla', 'skylar']",
 "['comred', 'eurbla', 'skylar', 'sonthr1']",
 "['comred', 'silver3', 'skylar']",
 "['maslap1', 'skylar']",
 "['auspip3', 'comred', 'yellow2']",
 "['comcha', 'comred', 'skylar', 'yellow2']",
 "['comred', 'skylar', 'sonthr1', 'yellow2']",
 "['comred', 'skylar', 'sonthr1']",
 "['ausmag2', 'skylar']",
 "['auspip3']",
 "['comcha', 'gryger1', 'sonthr1']",
 "['eurbla', 'nezfan1', 'silver3']",
 "['nezfan1', 'sackin1', 'silver3']",
 "['eurbla', 'silver3', 'skylar']",
 "['cangoo', 'eurgol', 'skylar']",
 "['cangoo', 'nezfan1', 'skylar', 'sonthr1']",
 "['cangoo', 'comcha', 'gryger1']",
 "['eurgol', 'skylar']",
 "['nezfan1', 'sonthr1']",
 "['comcha', 'nezfan1', 'skylar', 'sonthr1']",
 "['comcha', 'nezfan1', 'skylar']",
 "['nezfan1', 'sackin1', 'skylar']",
 "['nezfan1', 'sackin1']",
 "['nezfan1', 'sonthr1', 'tomtit1']",
 "['comcha', 'sonthr1', 'tomtit1']",
 "['gryger1', 'sackin1', 'sonthr1', 'tomtit1']",
 "['gryger1', 'sackin1', 'tomtit1']",
 "['nezfan1', 'skylar']",
 "['gryger1', 'sonthr1', 'tomtit1']",
 "['nezfan1', 'skylar', 'tomtit1']",
 "['eurgre1', 'sonthr1', 'yellow2']",
 "['eurgre1', 'yellow2']",
 "['eurgre1', 'sonthr1']",
 "['gryger1', 'nezbel1', 'silver3', 'sonthr1']",
 "['comcha', 'eurgol', 'eurgre1']",
 "['comcha', 'eurgol', 'silver3']",
 "['blfter1', 'comcha', 'gryger1', 'silver3']",
 "['eurgre1', 'eursta', 'silver3']",
 "['comcha', 'eursta', 'silver3']",
 "['comcha', 'sonthr1', 'yellow2']",
 "['comcha', 'eurgre1', 'gryger1']",
 "['comcha', 'eurgre1', 'silver3']",
 "['eurbla', 'silver3', 'sonthr1']",
 "['nezrob2', 'tomtit1']",
 "['eurbla', 'nezrob2']",
 "['gryger1', 'silver3', 'tui1']",
 "['gryger1', 'nezbel1', 'silver3', 'tui1']",
 "['comcha', 'gryger1', 'nezfan1', 'tomtit1']",
 "['comcha', 'nezbel1', 'nezfan1', 'tomtit1']",
 "['nezbel1', 'nezrob2', 'whiteh1']",
 "['nezfan1', 'nezrob2']",
 "['nezfan1', 'rebgul1', 'whiteh1']",
 "['kelgul', 'nezbel1', 'nezfan1', 'rebgul1', 'tui1', 'whiteh1']",
 "['nezfan1', 'tui1', 'whiteh1']",
 "['nezbel1', 'nezfan1', 'tui1', 'whiteh1']",
 "['nezfan1', 'tui1']",
 "['nezbel1', 'nezfan1', 'tui1']",
 "['rebgul1', 'whfter1']",
 "['rebgul1', 'whfter1', 'whiteh1']",
 "['gryger1', 'nezfan1', 'rebgul1', 'whfter1', 'whiteh1']",
 "['nezfan1', 'tui1', 'whfter1']",
 "['nezfan1', 'rebgul1']",
 "['rebgul1', 'tui1']",
 "['rebgul1']",
 "['ausmag2', 'skylar', 'yellow2']",
 "['ausmag2', 'dunnoc1', 'sackin1', 'skylar']",
 "['ausmag2', 'dunnoc1', 'skylar']",
 "['dunnoc1', 'sackin1', 'skylar', 'sonthr1', 'yellow2']",
 "['comcha', 'sackin1', 'skylar']",
 "['dunnoc1', 'sackin1', 'skylar']",
 "['comcha', 'sackin1', 'sonthr1', 'yellow2']",
 "['dunnoc1', 'skylar', 'sonthr1']",
 "['dunnoc1', 'skylar', 'sonthr1', 'yellow2']",
 "['comcha', 'eurbla', 'silver3', 'tui1']",
 "['comcha', 'silver3', 'tui1']",
 "['comcha', 'eurbla', 'silver3', 'tomtit1']",
 "['comcha', 'eurbla', 'gryger1', 'tomtit1', 'tui1']",
 "['comcha', 'gryger1', 'tui1']",
 "['eurbla', 'nezfan1', 'tomtit1']",
 "['comcha', 'tomtit1', 'yellow2']",
 "['dunnoc1', 'silver3']",
 "['comcha', 'eurgol', 'gryger1']",
 "['auspip3', 'silver3']",
 "['comcha', 'dunnoc1', 'tomtit1']",
 "['comcha', 'nezbel1', 'sonthr1']",
 "['comred', 'eurbla', 'yellow2']",
 "['comcha', 'comred', 'silver3', 'sonthr1']",
 "['comcha', 'comred', 'gryger1']",
 "['comred', 'gryger1', 'silver3']",
 "['comcha', 'comred', 'silver3']",
 "['comred', 'pipipi1', 'sonthr1']",
 "['comcha', 'gryger1', 'pipipi1', 'sonthr1']",
 "['comcha', 'comred', 'sonthr1']",
 "['comred', 'silver3', 'tomtit1']",
 "['comred', 'nezfan1', 'silver3', 'tomtit1']",
 "['maslap1']",
 "['purswa6']",
 "['parshe1']",
 "['gryger1', 'nezfan1', 'pipipi1']",
 "['nezfan1', 'pipipi1']",
 "['comred', 'nezfan1']",
 "['comcha', 'eurbla', 'nezfan1']",
 "['eurbla', 'nezbel1', 'pipipi1']",
 "['comred', 'eurbla', 'tomtit1']",
 "['comred', 'eurbla', 'nezbel1', 'tomtit1']",
 "['comcha', 'eurbla', 'tomtit1', 'tui1']",
 "['comred', 'eurbla', 'tui1']",
 "['comred', 'eurbla', 'sonthr1', 'tomtit1']",
 "['comred', 'nezbel1', 'tomtit1']",
 "['comred', 'sonthr1', 'tomtit1']",
 "['sonthr1', 'tomtit1']",
 "['eurbla', 'lotkoe1', 'tomtit1']",
 "['eurbla', 'lotkoe1', 'nezbel1', 'tomtit1']",
 "['eurbla', 'lotkoe1', 'nezbel1']",
 "['eurgre1', 'nezbel1', 'tomtit1']",
 "['comcha', 'comred', 'nezrob3', 'silver3', 'tui1']",
 "['comred', 'nezbel1', 'silver3', 'tui1']",
 "['comcha', 'eurbla', 'riflem1']",
 "['gryger1', 'silver3', 'sonthr1', 'tomtit1']",
 "['comred', 'nezrob2', 'tomtit1']",
 "['nezrob2', 'tomtit1', 'weka1']",
 "['tomtit1', 'weka1']",
 "['nezbel1', 'tomtit1', 'weka1']",
 "['nezbel1', 'weka1']",
 "['nezbel1', 'nezrob3', 'riflem1', 'tomtit1']",
 "['nezbel1', 'nezrob2', 'riflem1', 'tomtit1']",
 "['comcha', 'nezrob3', 'tomtit1']",
 "['eurbla', 'nezbel1', 'riflem1', 'sonthr1', 'tui1']",
 "['eurbla', 'riflem1', 'tui1']",
 "['eurbla', 'nezbel1', 'riflem1']",
 "['comcha', 'gryger1', 'nezbel1', 'nezrob3']",
 "['comcha', 'nezbel1', 'riflem1']",
 "['comcha', 'eurbla', 'gryger1', 'nezbel1', 'tomtit1', 'tui1']",
 "['comcha', 'eurbla', 'gryger1', 'nezbel1', 'tui1']",
 "['comcha', 'eurbla', 'gryger1', 'nezbel1', 'silver3']",
 "['nezrob3', 'sonthr1']",
 "['nezrob3', 'silver3', 'sonthr1']",
 "['gryger1', 'nezrob3', 'silver3']",
 "['comcha', 'eurbla', 'yellow2']",
 "['comcha', 'eurbla', 'silver3', 'yellow2']",
 "['comcha', 'silver3', 'yellow2']",
 "['comcha', 'comred', 'eurbla', 'sonthr1']",
 "['comred', 'eurbla', 'sonthr1']",
 "['comcha', 'nezfan1', 'silver3', 'sonthr1']",
 "['comred', 'eurbla', 'silver3', 'sonthr1']",
 "['comcha', 'eurbla', 'silver3', 'sonthr1']",
 "['comcha', 'nezfan1', 'silver3']",
 "['comcha', 'comred', 'eurbla', 'silver3']",
 "['comcha', 'comred', 'eurbla', 'nezfan1', 'silver3']",
 "['comcha', 'eurbla', 'nezfan1', 'silver3']",
 "['lotkoe1', 'nezkak1']",
 "['lotkoe1', 'nezbel1', 'nezkak1']",
 "['comcha', 'lotkoe1', 'nezkak1', 'tomtit1']",
 "['comcha', 'lotkoe1', 'nezkak1']",
 "['comcha', 'lotkoe1', 'nezbel1', 'nezkak1']",
 "['comcha', 'gryger1', 'lotkoe1']",
 "['comcha', 'gryger1', 'lotkoe1', 'nezbel1']",
 "['eurbla', 'silver3', 'weka1']",
 "['eurbla', 'nezbel1', 'tomtit1', 'weka1']",
 "['nezbel1', 'nezrob2', 'silver3']",
 "['comcha', 'nezbel1', 'nezrob3', 'riflem1', 'tomtit1', 'tui1']",
 "['comcha', 'nezbel1', 'nezrob3', 'riflem1', 'tomtit1']",
 "['comcha', 'gryger1', 'nezbel1', 'tomtit1', 'tui1']",
 "['comcha', 'nezfan1', 'nezrob3', 'riflem1', 'tomtit1']",
 "['comcha', 'riflem1', 'tomtit1', 'tui1']",
 "['comcha', 'nezbel1', 'riflem1', 'tomtit1', 'tui1']",
 "['comcha', 'eurbla', 'tui1']",
 "['eurbla', 'nezrob2', 'silver3', 'tui1']",
 "['nezrob2', 'silver3', 'tui1']",
 "['eurbla', 'gryger1', 'nezrob3', 'tomtit1']",
 "['eurbla', 'nezbel1', 'nezkak1', 'tomtit1']",

In [830]:
df.to_csv(paths.OUTPUT_CSV_PATH, index=False)

## Varify the audiofiles

I would like to be sure that the audio files can be opend OK

In [831]:
import torchaudio
import torch
import numpy as np


def crop_or_pad(y, length,  train='train', background_paths=None):
    initial_length = len(y)
    if 3 * initial_length < length:
        y = np.concatenate([y,np.zeros(initial_length),y])
    elif 2 * initial_length < length:
        y = np.concatenate([y,np.zeros(initial_length//2),y])
    if len(y) < length:
        y = np.concatenate([y, y]) 
    
    def Normalize(array):
        max_vol = np.abs(array).max()
        return array * 1 / max_vol

    if len(y) < length:
        difference = length - len(y)
        fill=np.zeros(difference)
        y = np.concatenate([y, fill])
    else:
        if train != 'train':
            start = 0
        else:
            start = 0
            start = np.random.randint(len(y) - length)
        y = y[start: start + length]
    y = Normalize(y)
    return y

def open_audio_clip(path, starts=None):    
    try:  
        y, _ = torchaudio.load(path)
        if y.ndim == 2 and y.shape[0] == 2:
            print(f'converting {path} to mono')
            y = torch.mean(y, dim=0).unsqueeze(0)  # from stereo to mono
        y = y.squeeze().numpy() 
    except Exception as e:
        y = np.random.randn(5*320000) 
        print(f'could not open {path}')
        print(e)
    
    if not np.isfinite(y).all():
        y[np.isnan(y)] = np.mean(y)
        y[np.isinf(y)] = np.mean(y)

    y = crop_or_pad(y, 10)  # background_paths=self.back_pths
    return y

In [832]:
tier1_files = [str(paths.DATA_FOLDER / fn) for fn in df_1['filename'].to_list()]
graeme_files = [str(paths.DATA_FOLDER / fn) for fn in df_2['filename'].to_list()]
xeno_files = [str(paths.DATA_FOLDER / fn) for fn in df_3['filename'].to_list()]

tier1_files[:5]

['/media/olly/T7/Kaytoo/Data/Train_Tier1/train_audio/yefpar3/AE142_BIRP_120321_124316_000.flac',
 '/media/olly/T7/Kaytoo/Data/Train_Tier1/train_audio/pipipi1/AE142_BIRP_120321_124316_001.flac',
 '/media/olly/T7/Kaytoo/Data/Train_Tier1/train_audio/pipipi1/AE142_BIRP_120321_124316_002.flac',
 '/media/olly/T7/Kaytoo/Data/Train_Tier1/train_audio/pipipi1/AE142_BIRP_120321_124316_003.flac',
 '/media/olly/T7/Kaytoo/Data/Train_Tier1/train_audio/pipipi1/AE142_BIRP_120321_124316_004.flac']

In [833]:
def play_audio(file_path):
    audio_abe, sr_abe = torchaudio.load(file_path)
    return Audio(data=audio_abe, rate=sr_abe)

play_audio(tier1_files[0])

In [834]:
play_audio(tier1_files[100])

In [835]:
play_audio(graeme_files[1])